name: flutter_admin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  rxdart: ^0.27.0
  google_fonts: 6.1.0
  flutter_lints: ^2.0.0
  country_picker: ^2.0.25
  percent_indicator: ^4.2.3
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.4
  material_design_icons_flutter: ^7.0.7296
  dotted_decoration: ^2.0.0
  qr_flutter: ^4.1.0
  intl: ^0.18.1
  table_calendar: ^3.0.8
  firebase_core: ^2.19.0
  firebase_auth: ^4.12.0
  firebase_storage: ^11.4.0
  provider: ^6.0.5
  flutter_verification_code: ^1.1.7
  cloud_firestore: ^4.15.6
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  external_app_launcher: ^3.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.1.0
  firebase_messaging: ^14.7.10
  rive: ^0.12.3
  lottie: ^3.0.0
  page_transition: ^2.1.0
  overlay_support: ^2.1.0
  flutter_local_notifications: ^16.3.2
  flutter_launcher_icons: ^0.13.1
  awesome_snackbar_content: ^0.1.3
  another_carousel_pro: ^1.0.2
  awesome_dialog: ^3.2.0
  quickalert: ^1.0.2
  flutter_localization: ^0.2.0
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.0.2
  qr_code_scanner: ^1.0.1
  flutter_barcode_scanner: ^2.0.0
  simple_barcode_scanner: ^0.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: BoonHome
      fonts:
        - asset: fonts/BoonHome-400.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
