// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU5FIj_jY2yN3-DyheYTjXJgfhDHmAxFE',
    appId: '1:219421571653:web:51daa735318f750468412c',
    messagingSenderId: '219421571653',
    projectId: 'flutterfinal-b4857',
    authDomain: 'flutterfinal-b4857.firebaseapp.com',
    databaseURL:
        'https://flutterfinal-b4857-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterfinal-b4857.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxAPOWnWTClBHdorXB0jCpjLKffNje_Os',
    appId: '1:219421571653:android:b51473763b4320c068412c',
    messagingSenderId: '219421571653',
    projectId: 'flutterfinal-b4857',
    databaseURL:
        'https://flutterfinal-b4857-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterfinal-b4857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSy9hVwl1E2S-XMv_w_iTSiGVP6PcawpA',
    appId: '1:219421571653:ios:818e9b7bd3ce867d68412c',
    messagingSenderId: '219421571653',
    projectId: 'flutterfinal-b4857',
    databaseURL:
        'https://flutterfinal-b4857-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterfinal-b4857.appspot.com',
    iosBundleId: 'com.example.flutterFinal',
  );
}
